print("****************")
print("Hamburguesas el corral")
print("****************")
nombreUsuario=input("Digite su usuario: ")
cedulaUsuario=input("Digite su cedula: ")
pedidoUsuario=input("Que hamburguesa quiere pedir: ")
valorPedido=int(input("Valor del pedido: "))
cantidadPedido=int(input("Cuantas hamburguesas quiere: "))
print("***************")
print("***************")
print(pedidoUsuario)
print(cantidadPedido)
print(valorPedido*cantidadPedido)